# Site settings
title: Hyssopus officinalis
email: hello@hyssop.io
description: > # this means to ignore newlines until "baseurl:"
  Hyssop is a group of web designers and developers.
  Like hyssop, we are small.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: hyssopgroup
github_username:  hyssopgroup

# Build settings
markdown: kramdown
